name: lazy_cam
description: A Flutter application to manage training.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

  # Camera
  camera: ^0.9.2+2

  # Image converters
  image: ^3.0.4          # Incompatible with integration_test -> Action to comment integration_test

  # State management
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  freezed_annotation: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Test-Lab
  #integration_test:
  #  sdk: flutter

  # Generators
  build_runner: 2.1.2
  freezed: ^0.14.5

  # Linter
  lint: ^1.5.2

flutter:
  uses-material-design: true
